---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name  }}-appserver
  labels:
    app: {{ template "yelb.fullname" . }}
    tier: middletier
    release: {{ .Release.Name }}
    chart: {{ template "yelb.chart" . }}
spec:
  type: ClusterIP
  ports:
  - port: 4567
  selector:
    app: {{ template "yelb.fullname" . }}
    tier: middletier
    release: {{ .Release.Name }}
