---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ui
  labels:
    app: {{ template "yelb.fullname" . }}
    tier: frontend
    chart: {{ template "yelb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port1 }}
    protocol: TCP
    targetPort: 80
    name: http
  - port: {{ .Values.service.port2 }}
    protocol: TCP
    targetPort: 80
    name: https
  selector:
    app: {{ template "yelb.fullname" . }}
    tier: frontend
    release: {{ .Release.Name }}
