# Default values for yelb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
#Replace my_gitlab_instance and my_namespace
imageBackend: my_gitlab_instance:5050/my_namespace/slurm-final-project-application/yelb-appserver
imageFrontend: my_gitlab_instance:5050/my_namespace/slurm-final-project-application/yelb-ui
imageTag: main.142
imagePullSecret: my-registry-secret

#Yelb environment values
yelbrackenv: custom
yelbdbhost: somehost.mdb.yandexcloud.net
yelbdbpassword: verystrongpassword
yelbdbuser: yelb-db-user
yelbdbport: 6432
yelbdbname: yelb-db

#Yelb Redis values
redishost: somehost.mdb.yandexcloud.net
redisport: 6379
redispassword: verystrongpassword

service:
  type: ClusterIP
  port1: 80
  port2: 443

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - yelb.domain_example.com
  tls: 
    - secretName: yelb-tls
      hosts:
        - yelb.domain_example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
